# Generated by Django 3.0.8 on 2021-07-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=2000, unique=True)),
                ('eta', models.DateField()),
                ('complete', models.BooleanField(default=False)),
            ],
        ),
    ]
